[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "${MQTT_BASE_TOPIC}/events",
    "${MQTT_BASE_TOPIC}/status"
  ]
  data_format = "json_v2"
  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "fire_detection"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "fire_score"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "vision_confidence"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "raw_avg_temp"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "uptime_seconds"
      type = "float"
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "decision"
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "door_state"
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "type"
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "sim_active"
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "gas_detected"
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "temp_flagged"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUXDB_ADMIN_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
